# SearXNG Meta Search Engine Only - Development Configuration
version: "3.8"

services:
  # SearXNG Meta Search Engine
  searxng:
    image: searxng/searxng:2025.8.8-5e7109c
    container_name: brainlens-searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:ro
      - searxng-cache:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_URL=http://localhost:8080/
    networks:
      - brainlens-searxng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  searxng-cache:
    driver: local

networks:
  brainlens-searxng:
    driver: bridge