# Qdrant Development Configuration for BrainLens

service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334

storage:
  # Storage configuration
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  
  # Performance settings for development
  wal_capacity_mb: 32
  wal_segments_ahead: 0
  
  # Indexing settings
  performance:
    max_search_threads: 2
    max_optimization_threads: 1
  
  # HNSW configuration for text embeddings (1536 dimensions from OpenAI)
  hnsw_config:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000

telemetry:
  disabled: true

log_level: INFO

# Cluster configuration (disabled for development)
cluster:
  enabled: false

# Web UI configuration  
web_ui:
  enabled: true